### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-pub-ui#10]
Any thoughts on updating these messages?

---

#### When the filers endpoint fails

This is also showing that we could update the placeholder text because if this happens the input is disabled.

![not-loaded](https://user-images.githubusercontent.com/2932572/37772960-ac96a8cc-2db2-11e8-9334-2b2f69d39b66.png)

---

#### When we can't find a filer from the front-end (the endpoint worked, the filer just isn't in the list)

![not-found](https://user-images.githubusercontent.com/2932572/37772965-b155fe58-2db2-11e8-8860-0739f2c13891.png)

**Comment by designlanguage** [comment]
@awolfe76 - How about we change the appearance of the input field when the endpoint fails? Could be the red outline from the USDS standards, or a light gray fill. I'm not sure if we would also need text inside it, but if so, I'd prefer something like "Error".

![screen shot 2018-03-22 at 9 40 13 am](https://user-images.githubusercontent.com/10562544/37773879-26d212dc-2db5-11e8-9d22-047e0767858d.png)

**Comment by awolfe76** [comment]
@designlanguage - No problem there. I was also curious about the messages.

Should we add something to the endpoint failure, like "Try to refresh the page" and "If this problem continues please contract HMDA help"?

And to the "can't find" error, like "If you think we are missing an institution, please contact HMDA help"?

**Comment by awolfe76** [comment]
Updates:

#### Endpoint fails

![no-filers](https://user-images.githubusercontent.com/2932572/37783079-efc7c348-2dca-11e8-824e-5d38e0abc427.png)


#### Not in the list

![not-found](https://user-images.githubusercontent.com/2932572/37783083-f3b6f6d6-2dca-11e8-8e04-9384a30f8315.png)

**Comment by colleenms** [comment]
For the scenario where the institution is not found, I would remove the second sentence. Based on feedback from clearance, we will likely be adding language to the top of the page further explaining that some institutions are no longer required to file or may not have filed yet, which will hopefully explain a lot of the institution not found results. Also, HMDA Help won't be very useful if the institution being searched is not in our panel or is in panel but hasn't filed.

**Comment by awolfe76** [comment]
> For the scenario where the institution is not found, I would remove the second sentence.

My thought here was the scenario where a filer had directed someone to this page and, for one reason or another, that institution didn't show up even though it is a _known_ filer. That's unlikely but still possible.

I'm ok removing that sentence but just want to make sure it's ok.

**Comment by designlanguage** [comment]
Ah, okay. In that case, I think it's better to feel like there's a path forward than just hitting a wall.
