### ISSUE TITLE
Reports missing total lines

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-pub-ui#120]
The following reports should include an "MSA/MD (TOTAL)" line:

- Aggregate Report 1 
- Disclosure Report 1
- Aggregate Report 2
- Disclosure Report 2

**Comment by wpears** [comment]
It looks like the totals aren't available in any of Agg/disc files for Reports 1 and 2. If we want to maintain consistency in the files themselves, we'll need to regenerate these tables and then the frontend will just automatically work.

If this is too onerous, we can write some logic in the client-side table components that calculates the totals from the data, but I think the preferred solution would be to maintain consistency by fixing the tables on the backend.

**Comment by awolfe76** [comment]
Closing this one for now.

We should update the files themselves in the future.
