### ISSUE TITLE
List and group reports

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-pub-ui#133]
From #57 

> Since there will always be the same reports for every MSA/MD, I don't think we need a dropdown. We can list them all, and have each link to a new tab or browser window, so if someone wants to view multiple reports at a time they can.

![](https://user-images.githubusercontent.com/10562544/38947054-5e8101f2-4309-11e8-8938-d832589b52df.png)

**Comment by wpears** [comment]
I'm not strictly against this, but I don't know if we need it, or rather I'd like to talk more about the justification. Is it just that links are simpler/easier to grok?

**Comment by wpears** [comment]
Yeah I was thinking that would be a good middle ground as well.
