### ISSUE TITLE
Reintroduce A4 once S3 is updated

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-pub-ui#149]
Specifically for Disclosure

**Comment by awolfe76** [comment]
@keileyo - We can go ahead and get the front-end ready for these but I just want to make sure what the `label` should be for `A4` and `A4W`?

This is what we currently have
- [for the `Ax` reports](https://github.com/cfpb/hmda-pub-ui/blob/1a804cc6d69028312150b0b4f8126a98ecd0d36d/src/constants/disclosure-reports.js#L194-L209)
- and [for the `AxW` reports](https://github.com/cfpb/hmda-pub-ui/blob/1a804cc6d69028312150b0b4f8126a98ecd0d36d/src/constants/disclosure-reports.js#L214-L228).

_These values are what gets displayed in the dropdown._

**Comment by keileyo** [comment]
For A4W: Preapproval Conv-Home-Pur First - Nationwide
For A4: Preapproval Conv-Home-Pur First 
For BW: Conv Price Info by Incidence and Level - Nationwide
