### ISSUE TITLE
Add Snapshot Loan Level Data on pub homepage

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#15]
To the /hmda-publication home page, add a new data product:

## Snapshot National Loan-Level Dataset
The snapshot file contains the national loan-level dataset as of a specific point in time for all HMDA reporters, as modified by the Bureau to protect applicant and borrower privacy.
Expected May 2018

The Expected May 2018 should be in the the style of the yellow "coming soon" tag that we have on A&D reports

**Comment by awolfe76** [comment]
Closed by #16.
