### ISSUE TITLE
Update dynamic dataset description

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#188]
The dynamic dataset intro text needs a couple of updates:

1) need a space between "and" and "borrower"

2) the second sentence begins with "The snapshot files..." and it should say "The dynamic files...." 

@awolfe76 we would like to send an email notifying users of the availability early next week, can we try to fix these before Tuesday, 8/6?

**Comment by wpears** [comment]
Fixed in master 😅

**Comment by keileyo** [comment]
thanks @wpears!
