### ISSUE TITLE
LAR Formatting Tools can't be opened on tools page

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#19]
The LAR Formatting Tools (2017 and 2018) are not able to be opened after the switchover from for filers to ffiec.cfpb.gov.  They can be downloaded, but an error message pops up when opening the file. 

![image](https://user-images.githubusercontent.com/13036571/38139167-41b9877c-33fc-11e8-8fdb-3f69d4ed673f.png)

@awolfe76 or @wpears can you take a look? I would say this is high priority to fix since the link on for filers already redirects to tools.

**Comment by awolfe76** [comment]
Closing this one ... see https://github.com/cfpb/hmda-platform-tools/issues/127.
