### ISSUE TITLE
LAR data files for Snapshot and Dynamic data have different specifications

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-pub-ui#192]
Should we standardize our LAR data schemas for 2017 so that users can more easily switch between the two?

Differences:
Dynamic has record ID and does not have As of Date, Edit Status, Sequence Number, or Application Date Indicator.

Some column names differ slightly between the two file specifications:
Occupancy vs Owner Occupancy
Preapproval vs Preapprovals
Action Type vs Type of Action Taken
Purchaser Type vs Type of Purchaser

**Comment by nickgrippin** [comment]
@keileyo, what do you think of adding this note (credit to @Kibrael) to the dynamic/snapshot publication pages?  

Snapshot data has preserved some elements of historic LAR data files that are not present in the Dynamic Data. These columns are "As of Date", "Edit Status", "Sequence Number", and "Application Date Indicator".  Be aware that data load procedures that handle both files will need to recognize this difference.

**Comment by keileyo** [comment]
Whoops sorry for a very delayed response here. I'm fine with the note being added, but would change "As of Date" to "As of Year" as its described in the LAR code schema [pdf](https://s3.amazonaws.com/cfpb-hmda-public/prod/snapshot-data/2017_publicstatic_dataformat.zip). I do not think we should spend any time standardizing the schemas.
