### ISSUE TITLE
Updates for 2018 data

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-pub-ui#229]
We can start to get the publication UIs ready for the 2018 data; modified LAR, disclosure reports, and aggregate reports.

We'll need to:

- [x] allow for toggling between years
- [x] update content
- [x] update specs
- [x] update the list of available reports

**Comment by keileyo** [comment]
@wpears the modified LAR page will need to be further updated to include a link to the 2018 modified LAR specification: 

My thought is just changing the current sentence "The modified LAR file specification is now available." to "Modified LAR file specifications: [2018](https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/Modified%20LAR%20Schema.csv), [2017](https://github.com/cfpb/hmda-platform/blob/master/docs/v1/2017_Modified_LAR_Spec.csv)"
