### ISSUE TITLE
A&D report format & download availability

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#23]
For initial release, we need to offer individual aggregate, disclosure & national aggregate reports for display and download:
1. Render JSON tables into a table that can be viewed in the UI and printed
2. CSV download of each report 

Reports should be available on an individual basis*
1. Disclosure reports by chosen institution & MSA
2. Aggregate reports by chosen state & MSA
3. Each national aggregate report individually 

*For initial release, we do not need to offer the option to download multiple reports at once (i.e. ALL aggregate reports for a selected MSA or all of an institution's disclosure reports for a given MSA).  We should consider a strategy that would allow us to add this functionality if we receive that feedback.

**Comment by awolfe76** [comment]
[An (old) example](https://github.com/cfpb/hmda-viz-prototype/blob/81e9674c232047ef41c56d578e66984622deb1a5/js/app.js#L215-L246) using the table instead of the JSON.
