### ISSUE TITLE
Snapshot dataset page needs new content/per year content

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-pub-ui#238]

**Comment by BarakStout** [comment]
Snapshot content: 

- [ ] 2018_public_lar_csv.zip
- [ ] 2018_public_lar_txt.zip
- [ ] 2018_public_ts_csv.zip
- [ ] 2018_public_ts_txt.zip
- [ ] 2018_public_panel_csv.zip
- [ ] 2018_public_panel_txt.zip
- [ ] 2018_public_msamd_csv.zip
- [ ] 2018_public_msamd_txt.zip
- [ ] 2018_publicstatic_dataformat.pdf
- [ ] 2018_publicstatic_codesheet.pdf

**Comment by chynnakeys** [comment]
2018_publicstatic_codesheet.pdf can be found here: https://github.com/cfpb/hmda-platform/blob/master/docs/v2/spec/2018_Public_LAR_Code_Sheet_PDF.pdf
@BarakStout

**Comment by chynnakeys** [comment]
Change year in intro paragraph for 2018 to "The snapshot files contain the national HMDA datasets as of August 7, 2019 for all HMDA reporters, as modified by the Bureau to protect applicant and borrower privacy. The snapshot files are available to download in both .csv and pipe delimited text file formats, and the file specification files are available to download in PDF format."

**Comment by chynnakeys** [comment]
Remove "Snapshot data has preserved some elements of historic LAR data files that are not present in the Dynamic Data. These columns are "As of Date", "Edit Status", "Sequence Number", and "Application Date Indicator". Be aware that data load procedures that handle both files will need to recognize this difference." paragraph for 2018. This is not applicable.

**Comment by chynnakeys** [comment]
@wpears can we also change the snapshot description on the data publication home page? it includes the 4/18/18 date. it should be changed to "The snapshot files contain the national HMDA datasets as of a fixed date per year for all HMDA reporters, as modified by the Bureau to protect applicant and borrower privacy."
