### ISSUE TITLE
MLAR File download from IE

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#253]
Currently, modified LAR files downloaded from IE are served in the browser instead of downloading the text file. Look into AWS settings to see if we can change this behavior in IE to downloading the files.

**Comment by zencircle** [comment]
Select File within S3 bucket --> Actions --> Change metadata --> Add
Key: Content-Dispostion; Value: attachment
![image](https://user-images.githubusercontent.com/25303681/55253221-26d3d900-522b-11e9-9241-d4c7714c4012.png)

**Comment by zencircle** [comment]
Permananet fix : https://github.com/cfpb/hmda-platform/issues/2660

**Comment by wpears** [comment]
Closing in light of 2660, thanks for the manual updates @zencircle
