### ISSUE TITLE
Add Resources and Instructions for Modified LAR users

### ISSUE THREAD

**Issue by ericspry** [cfpb/hmda-pub-ui#254]
Using the Modified LAR data from the [download page](https://ffiec.cfpb.gov/data-publication/modified-lar) requires several steps that are not likely to be familiar to many users of the data. For example:

*  File spec. Users need to know that with github you download the "raw" file 
*  File spec. To use as column headers in a spreadsheet like Excel, you have to transpose column to header
*  Importing to a spreadsheet like Excel: Spec file is `.csv` with `,` delimiter, and mLAR is `.txt`with `|` delimiter. Describe steps.  
* Once imported, the user will need a data dictionary understand field values 

Some of these can be solved simply, by adding a few instructions and resource links. We might also consider providing some common spreadsheet files for download with headers already setup.

**Comment by Kibrael** [comment]
[HMDA-Platform Issue](https://github.com/cfpb/hmda-platform/issues/2683)

**Comment by Kibrael** [comment]
In reference to providing common spreadsheet files for download with headers set up, could we publish headers on the MLAR data?

**Comment by Kibrael** [comment]
[2018 MLAR header CSV](https://drive.google.com/open?id=1695b7BSeLgSoWjM3XsjKxROnpH1f7Iku)

**Comment by Kibrael** [comment]
MLAR instructions doc suggestions:
- what is an MLAR (single institution's submission modified for privacy)
- which fields are removed from LAR for privacy reasons
- which fields are modified (and how) for privacy reasons
- which columns have mixed datatypes
- which fields can contain NA
- which fields can contain exempt
- how to load MLAR to Excel and split data using pipe-delimiter

**Comment by MichaelFurey17** [comment]
# Using Modified LAR Data
Modified LAR is the public-facing set of the Loan Application Register data 
containing fields that are altered or removed for privacy reasons.
Please refer to the schemas or Regulation C for further details on 
Modified LAR disclosure. 

## Opening Modified LAR Text Files With Excel
Modified LAR is downloaded as a pipe-delimited .txt file without descriptive 
headers. To read this file in Excel, the following steps would need to be 
taken.

1. Open the .txt file download with Excel. 
2. A window will open to select options for Excel to read the file. 
Select "Delimited" in the first window. Click next. 
3. Under delimiters, select "Other" and place a pipe ("|") in the "Other" 
field. Click Next.
4. On the last screen select "General" for data type, and select "Finish." 
At this point, the data will populate into their own cells.
5. Download the Modified LAR Headers File, open the file in Excel, and copy the 
first row into your modified LAR excel sheet.

At this point, the Modified LAR download would have the appropriate column 
headers. 

## Code Guide
The following code guide provides an overview of the Modified LAR sheet, the 
fields included, fields modified, and new fields added.

### Fields and Data Types for Modified LAR
1.	 Record Identifier - *Data Type: Integer*


2.	 Legal Entity Identifier(LEI) - *Data Type: Character Varying*


3.	 Loan Type - *Data Type: Integer* 


4.	 Loan Purpose - *Data Type: Integer* 


5.	 Preapproval - *Data Type: Integer* 


6.	 Construction Method - *Data Type: Integer*


7.	 Occupancy Type - *Data Type: Integer* 


8.	 Loan Amount - *Data Type: Integer or Double* 


9.	 Action Taken - *Data Type: Integer* 


10.	 State - *Data Type: Character Varying*


11.	 County - *Data Type: Character Varying*


12.	 Census Tract - *Data Type: Character Varying* 


13.	 Ethnicity of Applicant or Borrower: 1 - *Data Type: Character Varying (Contains integers or blanks)*


14.	 Ethnicity of Applicant or Borrower: 2 - *Data Type: Character Varying (Contains integers or blanks)*


15.	 Ethnicity of Applicant or Borrower: 3 - *Data Type: Character Varying (Contains integers or blanks)*


16.	 Ethnicity of Applicant or Borrower: 4 - *Data Type: Character Varying (Contains integers or blanks)*


17.	 Ethnicity of Applicant or Borrower: 5 - *Data Type: Character Varying (Contains integers or blanks)*


18.	 Ethnicity of Co-Applicant or Co-Borrower: 1 - *Data Type: Character Varying (Contains integers or blanks)*


19.	 Ethnicity of Co-Applicant or Co-Borrower: 2 - *Data Type: Character Varying (Contains integers or blanks)*


20.	 Ethnicity of Co-Applicant or Co-Borrower: 3 - *Data Type: Character Varying (Contains integers or blanks)*


21.	 Ethnicity of Co-Applicant or Co-Borrower: 4 - *Data Type: Character Varying (Contains integers or blanks)*


22.	 Ethnicity of Co-Applicant or Co-Borrower: 5 - *Data Type: Character Varying (Contains integers or blanks)*


23.	 Ethnicity of Applicant or Borrower Collected on the Basis of Visual Observation or Surname - *Data Type: 
Integer*


24.	 Ethnicity of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname - *Data Type: Integer*


25.	 Race of Applicant or Borrower: 1 - *Data Type: Character Varying (Contains integers or blanks)*


26.	 Race of Applicant or Borrower: 2 - *Data Type: Character Varying (Contains integers or blanks)*


27.	 Race of Applicant or Borrower: 3 - *Data Type: Character Varying (Contains integers or blanks)*


28.	 Race of Applicant or Borrower: 4 - *Data Type: Character Varying (Contains integers or blanks)*


29.	 Race of Applicant or Borrower: 5 - *Data Type: Character Varying (Contains integers or blanks)*


30.	 Race of Co-Applicant or Co-Borrower: 1 - *Data Type: Character Varying (Contains integers or blanks)*


31.	 Race of Co-Applicant or Co-Borrower: 2 - *Data Type: Character Varying (Contains integers or blanks)*


32.	 Race of Co-Applicant or Co-Borrower: 3 - *Data Type: Character Varying (Contains integers or blanks)*


33.	 Race of Co-Applicant or Co-Borrower: 4 - *Data Type: Character Varying (Contains integers or blanks)*


34.	 Race of Co-Applicant or Co-Borrower: 5 - *Data Type: Character Varying (Contains integers or blanks)*


35.	 Race of Applicant or Borrower Collected on the Basis of Visual Observation or Surname - *Data Type: Integer*


36.	 Race of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname - *Data Type: 
Integer*


37.	 Sex of Applicant or Borrower - *Data Type: Integer*


38.	 Sex of Co-Applicant or Co-Borrower - *Data Type: Integer*


39.	 Sex of Applicant or Borrower Collected on the Basis of Visual Observation or Surname - *Data Type: Integer*


40.	 Sex of Co-Applicant or Co-Borrower Collected on the Basis of Visual Observation or Surname - *Data Type: Integer*


41.	 Age of Applicant or Borrower - *Data Type: Character Varying*


42.	 Age of Applicant >= 62 - *Data Type: Character Varying*


43.	 Age of Co-Applicant or Co-Borrower - *Data Type: Character Varying*


44.	 Age of Co-Applicant >= 62 - *Data Type: Character Varying*


45.	 Income - *Data Type: Character Varying (Contains integers or 'NA')*


46.	 Type of Purchaser - *Data Type: Integer*


47.	 Rate Spread - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


48.	 HOEPA Status - *Data Type: Integer*


49.	 Lien Status - *Data Type: Integer*


50.	 Applicant or Borrower - Name and Version of Credit Scoring Model - *Data Type: Integer*


51.	 Co-Applicant or Co-Borrower - Name and Version of Credit Scoring Model - *Data Type: Integer*


52.	 Reason for Denial: 1 - *Data Type: Integer*


53.	 Reason for Denial: 2 - *Data Type: Character Varying (Contains integers or blanks)*


54.	 Reason for Denial: 3 - *Data Type: Character Varying (Contains integers or blanks)*


55.	 Reason for Denial: 4 - *Data Type: Character Varying (Contains integers or blanks)*


56.	 Total Loan Costs - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


57.	 Total Points and Fees - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


58.	 Origination Charges - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


59.	 Discount Points - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


60.	 Lender Credits - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


61.	 Interest Rate - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


62.	 Prepayment Penalty Term - *Data Type: Character Varying (Contains integers, 'NA' or 'Exempt')*


63.  Debt-to-Income Ratio - *Data Type: Character Varying*


64.	 Combined Loan-to-Value Ratio - *Data Type: Character Varying (Contains doubles, 'NA' or 'Exempt')*


65.	 Loan Term - *Data Type: Character Varying (Contains integers, 'NA' or 'Exempt')*


66.	 Introductory Rate Period - *Data Type: Character Varying (Contains integers, 'NA' or 'Exempt')*


67.	 Balloon Payment - *Data Type: Integer*


68.	 Interest-Only Payments - *Data Type: Integer*


69.	 Negative Amortization - *Data Type: Integer*


70.	 Other Non-amortizing Features - *Data Type: Integer*


71.	 Property Value - *Data Type: Integer*


72.	 Manufactured Home Secured Property Type - *Data Type: Integer*


73.	 Manufactured Home Land Property Interest - *Data Type: Integer*


74.	 Total Units - *Data Type: Character Varying (Contains integers, 'NA' or 'Exempt')*


75.	 Multifamily Affordable Units - *Data Type: Character Varying (Contains integers, 'NA' or 'Exempt')*


76.	 Submission of Application - *Data Type: Integer*


77.	 Initially Payable to Your Institution - *Data Type: Integer*


78.	 Automated Underwriting System: 1 - *Data Type: Integer*


79.	 Automated Underwriting System: 2 - *Data Type: Character Varying (Contains integers, or blanks)*


80.	 Automated Underwriting System: 3 - *Data Type: Character Varying (Contains integers or blanks)*


81.	 Automated Underwriting System: 4 - *Data Type: Character Varying (Contains integers or blanks)*


82.	 Automated Underwriting System: 5 - *Data Type: Character Varying (Contains integers or blanks)*


83.	 Reverse Mortgage - *Data Type: Integer*


84.	 Open-End Line of Credit - *Data Type: Integer*


85.	 Business or Commercial Purpose - *Data Type: Integer*

### Fields Removed in the Modified LAR Data Release for Privacy 
1. Universal Loan Identifier (ULI) or Non Universal Loan Identifier (NULI)
2. Application Date
3. Action Taken Date
4. Street Address 
5. City
6. Zip Code
7. Ethnicity of Applicant or Borrower: Free Form Text Field for Other 
Hispanic or Latino
8. Ethnicity of Co-Applicant or Co-Borrower: Free Form Text Field for Other 
Hispanic or Latino
9. Race of Applicant or Borrower: Free Form Text Field for American Indian 
or Alaska Native Enrolled or Principal Tribe
10. Race of Applicant or Borrower: Free Form Text Field for Other Asian
11. Race of Applicant or Borrower: Free Form Text Field for Other Pacific 
Islander
12. Race of Co-Applicant or Co-Borrower: Free Form Text Field for American 
Indian or Alaska Native Enrolled or Principal Tribe
13. Race of Co-Applicant or Co-Borrower: Free Form Text Field for Other Asian
14. Race of Co-Applicant or Co-Borrower: Free Form Text Field for Other 
Pacific Islander
15. Credit Score of Applicant or Borrower.
16. Credit Score of Co-Applicant or Co-Borrower
17. Applicant or Borrower, Name and Version of Credit Scoring Model: 
Conditional Free Form Text Field for Code 8
18. Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model: 
Conditional Free Form Text Field for Code 8
19. Reason for Denial: Conditional Free Form Text Field for Code 9
20. Mortgage Loan Originator NMLSR Identifier
21. Automated Underwriting System: Conditional Free Form Text Field for Code 5
22. Automated Underwriting System Result: 1
23. Automated Underwriting System Result: 2
24. Automated Underwriting System Result: 3
25. Automated Underwriting System Result: 4
26. Automated Underwriting System Result: 5
27. Automated Underwriting System Result: Conditional Free Form Text Field for 
Code 16

### New Fields Added to Modified LAR
Age of Applicant >= 62
Description: Field that indicates whether the applicant or borrower has an
age greater than or equal to 62. 
1. 'Yes'if the age of the applicant is >= 62. 
2. 'No' if the age is <= 62. 
3. 'NA'if Age of Applicant or Borrower is 8888 or 9999

Age of Co-Applicant >= 62
Description: Field that indicates whether the applicant or borrower has an
age greater than or equal to 62. 
1. 'Yes'if the age of the applicant is >= 62. 
2. 'No' if the age is <= 62. 
3. 'NA'if Age of Applicant or Borrower is 8888 or 9999

Age of Co-Applicant >= 62

### Fields Modified for Privacy in the Modified LAR Data

Along with omitted fields, the modified LAR data contains the following 
alterations to reported values. 

Loan Amount 
Description: Each loan amount is listed as the midpoint into which the 
reported value falls (For example a reported value of $117834 would be 
disclosed $115000 as the midpoint between values = $110000 and < $120000). 

Applicant/Co-Applicant Age 
Description: Each age value is binned to the following categories:
1. Ages less than 25 - '<25'
2. Ages between 25 and 34 - '25-34' 
3. Ages between 35 and 44 - '35-44' 
4. Ages between 45 and 54 - '45-54'
5. Ages between 55 and 64 - '55-64'
6. Ages between 65 and 74 - '65-74'
7. Ages greater than 74 - '>74'

Debt-to-Income Ratio
Description: Exact values between 36% and less than 50% are disclosed as-is. 
Non-applicable values are disclosed as-is. Exempt values are disclosed as-is. 
All other categories are binned to the following:

1. Values less than 20% - '<20%'
2. Values between 20% and less than 30% - '20%-<30%'
3. Values between 30% and less than 36% - '30%-<36%'
4. Values between 50% and 60% - '50%-60%' 
5. Values greater than 60%. - '>60%'

Property Value 
Description: Each property value is listed as the midpoint into which the 
reported value falls (For example a reported value of $117834 would be 
disclosed as $115000 as the midpoint between values $110000 and $120000.

Total Units
Description: Exact values between 1 and 4 are disclosed. Other values are 
binned according to the following: 
1. Values between 5 and 24 - '5-24'
2. Values between 25 and 49 - '25-49' 
3. Values between 50 and 99 - '50-99'
4. Values between 100 and 149 - '100-149'
5. Values over 149 - '>149'

Multifamily Affordable Units
Description: Values that are not NA or Exempt are disclosed as a percentage 
calculated as multifamily affordable units reported / total units reported.
