### ISSUE TITLE
Create 2019 Aggregate Report- (Applications by Tract)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-pub-ui#258]
Applications by Tract refers to Table 1 from last year.
2017 Report Example: https://ffiec.cfpb.gov/data-publication/aggregate-reports/2017/MD/47894/1

## Sample Mockup:
![aggregate - apps by tract (table A) 3-21](https://user-images.githubusercontent.com/41752348/54848762-93455a00-4cb8-11e9-9e2d-ca9ade9c632c.jpg)

Changes from 2017: 
- Min Pop and Median Income columns are no longer included. 

- Rows labeled A-G are now above loan types labels in table.

- Amount is in whole dollar amount now, as opposed to being rounded to the nearest thousandth (e.g., $ 3 equated to $3000 in the 2017 report; this will now be reported as $3000)

## Note: Mockups include "Table A", but this has been revised and table names will not be labeled as letters, but instead as the description of the table.

**Comment by wpears** [comment]
Implemented in 2019-disclosure branch
