### ISSUE TITLE
Create 2019 Aggregate Report (Loans Purchased by Tract)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-pub-ui#259]
"Loans Purchased, BY LOCATION OF PROPERTY AND TYPE OF LOAN"

Loans Purchased by Tract refers to Table 2 from last year.
2017 Report Example: https://ffiec.cfpb.gov/data-publication/disclosure-reports/2017/451965/27180/2

## Sample Mockup: 
![aggregate - purchased loans by tract 3-21](https://user-images.githubusercontent.com/41752348/54848976-267e8f80-4cb9-11e9-8843-5665041af930.jpg)

Changes from 2017: 
- Rows labeled A-G are now above loan types labels in table. 

- Amount is in whole dollar amount now, as opposed to being rounded to the nearest thousandth (e.g., $ 3 equated to $3000 in the 2017 report; this will now be reported as $3000)

## Note: Mockups include "Table B", but this has been revised and table names will not be labeled as letters, but instead as the description of the table.

**Comment by wpears** [comment]
Implemented in 2019-disclosure branch
