### ISSUE TITLE
Create 2019 Aggregate Report (Applications by Median Age of Homes) 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-pub-ui#266]
## DISPOSITION OF LOAN APPLICATIONS, BY MEDIAN AGE OF HOMES AND TYPE OF LOAN

Applications by Median Age of Homes Table refers to Table 9 from last year.
2017 Report Example: https://ffiec.cfpb.gov/data-publication/aggregate-reports/2017/MD/47894/9

## Sample Mockup: 
![aggregate - median home age (table F) 3-21](https://user-images.githubusercontent.com/41752348/54926561-f0265780-4ee6-11e9-9f61-9bd26e0a5506.jpg)

Changes from 2017: 
- Amount is in whole dollar amount now, as opposed to being rounded to the nearest thousandth (e.g., $ 3 equated to $3000 in the 2017 report; this will now be reported as $3000)

- Row labeled A-G is now above loan types labels in table. 

## Note: Mockups include "Table F", but this has been revised and table names will not be labeled as letters, but instead as the description of the table.

**Comment by chynnakeys** [comment]
@omnipresent07 @PatrickHSI 
There appears to be a few issues with this table: 
1) Action taken 6: loans purchased is being displayed under action taken 3: loans denied. Loans purchased do not fall under a category in this table. 
Example:  
![image](https://user-images.githubusercontent.com/41752348/58266539-d91dad80-7d4f-11e9-88e0-cc82d4cac212.png)
![image](https://user-images.githubusercontent.com/41752348/58266583-f2265e80-7d4f-11e9-9538-31630d02742a.png)
2) The action taken rows appear to be triplicated in this table. 
3) Can we put the years in order? They currently are listed out of order and should be listed: 
2011 - PRESENT
2000 - 2010
1990 - 1999AGE UNKNOWN
1980 - 1989
1970 - 1979
1969 OR EARLIER

**Comment by omnipresent07** [comment]
@chynnakeys verified this is tested
