### ISSUE TITLE
Disclosure report: IRS

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#268]
IRS is the third disclosure report that we will offer. The front end will need to be adjusted slightly because the report structure is slightly different than 2017. 

2018 IRS csv attached to show row/column headers. 
[IRS example.txt](https://github.com/cfpb/hmda-pub-ui/files/3035217/IRS.example.txt)

The IRS is considered a Nationwide disclosure report, so we need to include the nationwide option when selecting MSA/MDs.  
![image](https://user-images.githubusercontent.com/13036571/55425791-4c295580-5551-11e9-97ef-027367887be0.png)

**Comment by wpears** [comment]
Implemented in 2019-disclosure branch
