### ISSUE TITLE
Rename Disclosure Tables

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#269]
Rename Table 1 to Table A

Rename Table 2 to Table B 

@wpears im adding this to the sprint 42 as i hope it should be a small change.

**Comment by omnipresent07** [comment]
@wpears Backend can provide this information in the json. i.e. Change `table: "1"` to `table: "A"`, however, doing so breaks the front end rendering of the json.

**Comment by wpears** [comment]
We're actually backing off on this and just labelling tables with their descriptions
