### ISSUE TITLE
Shorten Disclosure Report drop down options 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-pub-ui#270]
The drop down of disclosure reports should only include three tables. 

Under each MSA/MD chosen, the two options should be:
- Table A: Applications by Tract
- Table B: Loans Purchased by Tract 

Under the NATIONWIDE option when selecting an MSA/MD, the only option should be:
- IRS Table

**Comment by wpears** [comment]
Implemented in 2019-disclosure branch
