### ISSUE TITLE
Reported institutions aggregate report isn't being parsed

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-pub-ui#275]
Reported institutions aggregate report isn't being parsed and isn't rendering on the front end. A sample report is available here: http://s3.amazonaws.com/cfpb-hmda-public/dev/reports/aggregate/2018/49740/i.json

**Comment by PatrickHSI** [comment]
It looks like the chunk of code responsible for listing the institutions was looking for respondent id/name fields instead of an array of institutions.

**Comment by PatrickHSI** [comment]
<img width="1302" alt="Screen Shot 2019-04-19 at 12 09 16 PM" src="https://user-images.githubusercontent.com/44584592/56432758-a0943b00-629c-11e9-8e3f-13cbc345fd83.png">
