### ISSUE TITLE
Provide content that explain use cases for dataset supporting docs

### ISSUE THREAD

**Issue by MichaelFurey17** [cfpb/hmda-pub-ui#289]
The content should explain to users the differences between schemas, dictionaries, and codesheets, and the purpose of each resource listed.

**Comment by Kibrael** [comment]
This work is dependent on the finalization of supporting docs for LAR/TS/Panel datasets.

**Comment by Kibrael** [comment]
- Code Sheet: A quick reference guide containing the valid codes by field, intended for use during analysis.
- file specifications: Complete documentation for the dataset including field number, data type, valid values, and examples.
- Data Dictionary: A simplified version of the file specificaiton intended for easy conversion to SQL statements.
- Opening Modified LAR Text Files With Excel: Step by step instructions for opening an institution's Modified LAR file in Excel and adding the column names.
- header for CSV files: A list of column names for use with the Modified LAR text files.
- Modified LAR Field information: A discussion of the data available in the Modified LAR text files. Includes information on additional fields and how the base data was modified to protect the privacy of borrowers.

**Comment by wpears** [comment]
Added david's descriptions with #291. Closing for now, @MichaelFurey17 feel free to reopen if you want more here.
