### ISSUE TITLE
Create FIG announcement on ffiec.cfpb.gov

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-pub-ui#299]
An announcement needs to be made on ffiec.cfpb.gov for the 2019 FIG update. 

"The Bureau has released a minor update to the 2019 FIG." with the link to the 2019 FIG.

[Filing instructions guide for HMDA data collected in 2019.pdf](https://github.com/cfpb/hmda-pub-ui/files/3393458/Filing.instructions.guide.for.HMDA.data.collected.in.2019.pdf)

**Comment by wpears** [comment]
@chynnakeys How should the existing announcement be modified to accommodate this new one?

Example:
<img width="1000" alt="Screen Shot 2019-07-15 at 4 06 03 PM" src="https://user-images.githubusercontent.com/1558033/61254769-9dcda880-a71a-11e9-81a4-749b7b39106f.png">

I could also just drop the second line entirely, or insert whatever text you'd like.

**Comment by chynnakeys** [comment]
Hey @wpears, you can drop the second line
