### ISSUE TITLE
Search functionality to include institution name and respondent ID

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-pub-ui#3]
Allow users to search by a) institution name (respondent name in institutions API) or b) respondent id (externalId in institutions API)

![image](https://user-images.githubusercontent.com/32906749/37371199-fcb2894a-26e4-11e8-8cd9-79654a233555.png)

**Comment by awolfe76** [comment]
The initial push of this will just use institution name. We can definitely add this in later though.

(Same for part of #5)
