### ISSUE TITLE
Validate aggregate report via UI

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-pub-ui#301]
aggregate reports have been ran on entiredata set but they need to be verified:

- [x] deploy branch of pub-ui that includes making aggregate reports public
- [x] Reports 3 and 4 don't seem to be working. @wpears @PatrickHSI 
- [x] validate the aggregate reports look ok

**Comment by omnipresent07** [comment]
Issue with reports 3 and 4 fixed by @PatrickHSI via https://github.com/cfpb/hmda-pub-ui/pull/302/commits/e9820331c2be2b0d12276a5cd22b54d7613f5c7e

**Comment by wpears** [comment]
There will need to be a small code change to pub-ui when data is pushed to the prod bucket, https://github.com/cfpb/hmda-pub-ui/issues/303

**Comment by chynnakeys** [comment]
@wpears @omnipresent07 in the applications by tract and loans purchased by tract table, the header row list the order as (state/county/tract), but the geographies are listed as (county/state/tract). We should change the header to county/state/tract for consistency.

**Comment by omnipresent07** [comment]
@wpears mentioned report 1 and 2 had duplicated rows at times. 

Reports 1 and 2 have been re-run and _should_ not have the duplicated records in them any more. The root cause is a multitude of NA in State and/or County and implementation of [Q604](https://github.com/cfpb/hmda-platform/issues/2692)

**Comment by chynnakeys** [comment]
@wpears reports look fine now, the labels on tables 1 & 2 still need to be changed, though.

**Comment by wpears** [comment]
@chynnakeys The tables have been fixed, but the newest code just hasn't been deployed
