### ISSUE TITLE
Add link to Public Panel Values and Definitions to Dynamic and Snapshot Dataset Pages 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-pub-ui#324]
https://ffiec.cfpb.gov/documentation/2018/panel-data-fields/ should be linked on https://ffiec.cfpb.gov/data-publication/dynamic-national-loan-level-dataset/2018 and https://ffiec.cfpb.gov/data-publication/snapshot-national-loan-level-dataset/2018 pages

**Comment by wpears** [comment]
Closed by bad97992
