### ISSUE TITLE
Descriptor for modified LAR 

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-pub-ui#4]
On the HMDA Reporting page, the following can be displayed underneath the modified LAR title:

This report includes a financial institution's loan-level data, as modified by the Bureau to protect applicant and borrower privacy. The data shows the geographic distribution of loans and applications; ethnicity, race, sex, age, and income of applicants and borrowers; and information about loan approvals and denials.

@keileyo

**Comment by awolfe76** [comment]
Since we have a placeholder for the other report types, can we go ahead and get descriptions of those too? 

- Aggregate
- Disclosure
- National Aggregate

**Comment by keileyo** [comment]
1) Change the descriptor slightly to say:
"Modified LAR reports include a financial institution's....."

2) I think the header should be Modified Loan/Application Register (LAR)

**Comment by colleenms** [comment]
I suggest keeping the current description for Disclosure reports and changing the other two as follows:

- Aggregate: These reports summarize lending activity by MSA/MD.
- National Aggregate: These reports summarize nationwide lending activity. They indicate the number and dollar amounts of loan applications, cross-tabulated by loan, borrower and geographic characteristics.

**Comment by colleenms** [comment]
@awolfe76 Please update description to:

The modified LAR provides loan-level data for an individual financial institution, as modified by the Bureau to protect applicant and borrower privacy.
