### ISSUE TITLE
Report A-n

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-pub-ui#40]
An example of the report format can be found using [the current Aggregate tool](https://www.ffiec.gov/hmdaadwebreport/aggwelcome.aspx) or [the current Disclosure tool](https://www.ffiec.gov/hmdaadwebreport/diswelcome.aspx).

**Comment by wpears** [comment]
Closed by https://github.com/cfpb/hmda-pub-ui/pull/78
