### ISSUE TITLE
Language on modified LAR page

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-pub-ui#5]
On the search page, we can include the following language underneath the modified LAR title:

A downloadable modified LAR file is available for every financial institution that has filed a 2017 HMDA LAR. Using this form, you can search for a financial institution by name or respondent ID and download their modified LAR.

The title above the search box can then say: Enter an institution name or respondent ID

@keileyo

**Comment by keileyo** [comment]
Two small changes: 

1) Change "A downloadable modified LAR file is available for every financial institution that has filed a 2017 HMDA LAR." to "A downloadable modified LAR file is available for every financial institution that has completed a 2017 HMDA data submission." 

2) Let's change "their" to "its" in the last sentence.

**Comment by colleenms** [comment]
@awolfe76 Updated version:

A downloadable modified LAR file is available for every financial institution that has completed a 2017 HMDA data submission. Enter a financial institution’s name to download its modified LAR file. If you cannot find a particular financial institution using this form, the institution may not have been required to report HMDA data for 2017 or it may not have completed its 2017 HMDA data submission.
