### ISSUE TITLE
Link to eReg for an institution's reporting requirements

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-pub-ui#6]
It may be easiest to include a link to the eReg Disclosure & Reporting section on the Publications home page, under a section titled resources (similar to the one on the platform home page). here is the link:

https://www.consumerfinance.gov/eregulations/1003-5/2017-18284_20180101#1003-5-a

The above outlines an institution's obligations for modified LAR and A&D reports.

**Comment by awolfe76** [comment]
Not sure we need a new section for this, but definitely will get it included on the page.

**Comment by colleenms** [comment]
@awolfe76 We can remove the following sentence and link: 

Learn more about a financial institutions obligations for disclosure and reporting.
