### ISSUE TITLE
Publication heading

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-pub-ui#7]
Any thoughts on what this heading should be? (It's on the `/publication` page.)

![publication-heading](https://user-images.githubusercontent.com/2932572/37410521-2dfc9d78-2777-11e8-855c-6cadb80dc155.png)

**Comment by keileyo** [comment]
HMDA Data Publication is my suggestion

**Comment by awolfe76** [comment]
Sorry, meant to say "heading" and "description". Thoughts on the description too?

**Comment by designlanguage** [comment]
I know our team understand what "publication" means, but I wonder if filers do.

I was actually thinking "HMDA reporting should be repeated in the nav to replace "publication".

**Comment by awolfe76** [comment]
@designlanguage 

Something like
- `reporting/reports` (what we'll do initially)
- `reporting/charts` (later)
- `reporting/maps` (later)
- `reporting/<whatever>` (later)

**Comment by colleenms** [comment]
@awolfe76 Please update description to:

The HMDA data and reports are the most comprehensive publicly available information on mortgage market activity. The data and reports can be used along with the Census demographic information for data analysis purposes. Available below are the data and reports for HMDA data collected in or after 2017. For HMDA data and reports for prior years, visit https://www.ffiec.gov/hmda/hmdaproducts.htm.

Also, hyperlink the word Census to https://www.ffiec.gov/censusproducts.htm
